export const CONTENT_STUDIO_URI = "ui://trendhub/content-studio.html";

export const CONTENT_STUDIO_WIDGET = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root{color-scheme:light;--paper:#f6f0e4;--paper2:#ebe2d2;--ink:#2b2720;--muted:#786f61;--line:#d2c5b2;--maple:#a8472d;--maple2:#873321;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}*{box-sizing:border-box}body{margin:0;padding:14px;color:var(--ink);background-color:var(--paper2);background-image:repeating-linear-gradient(7deg,rgba(72,55,34,.018) 0 1px,transparent 1px 6px)}main{max-width:760px;margin:auto;padding:20px;border:1px solid var(--line);background:rgba(249,245,236,.95);box-shadow:0 12px 36px rgba(55,42,26,.08)}header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;border-bottom:1px solid var(--line);padding-bottom:14px}.k{color:var(--maple);font-size:10px;font-weight:750;letter-spacing:.16em;text-transform:uppercase}h1{margin:3px 0 0;font:700 24px/1.2 "Songti SC",STSong,serif}.state{font-size:11px;color:var(--muted)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}label{display:grid;gap:5px;color:var(--muted);font-size:10px;font-weight:650}input,select,textarea{width:100%;border:0;border-bottom:1px solid var(--line);border-radius:0;padding:8px;background:rgba(255,255,255,.3);color:var(--ink);font:13px/1.5 inherit}input:focus,select:focus,textarea:focus{outline:0;border-color:var(--maple)}textarea{min-height:190px;resize:vertical;font-family:"Songti SC",STSong,serif;line-height:1.8}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}button{min-height:36px;padding:0 13px;border:1px solid var(--line);border-radius:3px;background:transparent;color:var(--ink);font-weight:650;cursor:pointer}button.primary{border-color:var(--maple);background:var(--maple);color:#fffaf1}button.primary:hover{background:var(--maple2)}button:disabled{opacity:.55;cursor:wait}.evidence{margin-top:14px;padding:12px;border-left:2px solid var(--maple);background:rgba(168,71,45,.055);font-size:11px;line-height:1.65;color:var(--muted)}.evidence strong{color:var(--ink)}@media(max-width:560px){.grid{grid-template-columns:1fr}main{padding:16px}header{flex-direction:column}}
</style></head><body><main>
<header><div><span class="k">TrendHub 2.0 · Content Studio</span><h1>证据驱动的内容创作</h1></div><span class="state" id="state">等待简报</span></header>
<div class="grid"><label>主题<input id="topic" placeholder="真实主题、事件或品牌命题"></label><label>目标<input id="goal" placeholder="影响力、转化、教育或讨论"></label><label>受众<input id="audience" placeholder="谁需要看见并行动"></label><label>平台<select id="platform"><option value="xiaohongshu">小红书</option><option value="douyin">抖音</option><option value="wechat">公众号</option><option value="weibo">微博</option><option value="all">通用</option></select></label></div>
<label>可编辑制品<textarea id="draft" placeholder="先生成证据简报，再让当前 AI 直接产出成稿。"></textarea></label>
<div class="actions"><button id="brief">生成证据简报</button><button class="primary" id="create">让我的 AI 创作</button><button id="copy">复制制品</button></div>
<div class="evidence" id="evidence"><strong>事实墙：</strong>AI 输出不是证据；未知事实必须保留【待核验】。</div>
</main><script>
let nextId=1;const pending=new Map();let brief=null;const $=s=>document.querySelector(s);const state=t=>$("#state").textContent=t;
function request(method,params){const id=nextId++;window.parent.postMessage({jsonrpc:"2.0",id,method,params},"*");return new Promise((resolve,reject)=>pending.set(id,{resolve,reject}))}
function values(){return{topic:$("#topic").value.trim(),goal:$("#goal").value.trim(),audience:$("#audience").value.trim(),platform:$("#platform").value}}
function renderBrief(data){brief=data||brief;if(!brief)return;const cp=brief.evidence?.crossPlatform||{};const rq=brief.evidence?.relatedQueries||{};$("#evidence").innerHTML="<strong>证据状态：</strong>"+(cp.dataQuality||"unknown")+" · 平台命中 "+(cp.platformsHit??"—")+" · 公开提及 "+(cp.totalMentions??"—")+"<br><strong>关联语义：</strong>"+[...(rq.rising||[]),...(rq.top||[])].slice(0,8).map(x=>x.query).join("、")+"<br>未知事实继续标记【待核验】。";state("简报已就绪")}
function prompt(){const v=values();return "请使用我的当前 AI，基于 TrendHub 证据简报直接完成可编辑成稿，不要只给步骤。\\n主题："+v.topic+"\\n目标："+v.goal+"\\n受众："+v.audience+"\\n平台："+v.platform+"\\n证据简报："+JSON.stringify(brief||{},null,2)+"\\n输出：标题候选、完整正文或脚本、视觉/镜头建议、事实核验清单、发布前检查。只使用简报中的事实，未知项标【待核验】，保持原创。"}
async function getBrief(){const v=values();if(!v.topic)throw new Error("请先填写主题");state("正在收集公开证据…");const result=window.openai?.callTool?await window.openai.callTool("get_content_brief",v):await request("tools/call",{name:"get_content_brief",arguments:v});renderBrief(result?.structuredContent?.brief||result?.structuredContent||window.openai?.toolOutput);return brief}
$("#brief").onclick=async e=>{e.currentTarget.disabled=true;try{await getBrief()}catch(err){state(err.message||"简报失败")}finally{e.currentTarget.disabled=false}};
$("#create").onclick=async e=>{e.currentTarget.disabled=true;try{if(!brief)await getBrief();state("已交给当前 AI 创作");if(window.openai?.sendFollowUpMessage)await window.openai.sendFollowUpMessage({prompt:prompt(),scrollToBottom:true});else await request("ui/message",{role:"user",content:[{type:"text",text:prompt()}]})}catch(err){state(err.message||"AI 连接失败")}finally{e.currentTarget.disabled=false}};
$("#copy").onclick=()=>navigator.clipboard?.writeText($("#draft").value);$("#draft").oninput=()=>window.openai?.setWidgetState?.({topic:$("#topic").value,draft:$("#draft").value,stage:"create"});
window.addEventListener("message",event=>{if(event.source!==window.parent)return;const m=event.data;if(!m||m.jsonrpc!=="2.0")return;if(m.id!==undefined&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);return}if(m.method==="ui/notifications/tool-result")renderBrief(m.params?.structuredContent?.brief||m.params?.structuredContent)});
const input=window.openai?.toolInput||{};if(input.topic)$("#topic").value=input.topic;renderBrief(window.openai?.toolOutput?.brief||window.openai?.toolOutput);
</script></body></html>`;
